const vehicleTypeOptions = <String>[
  'Toyota Corolla',
  'Toyota Yaris',
  'Hyundai i10',
  'Hyundai i20',
  'Hyundai Accent',
  'Kia Picanto',
  'Kia Rio',
  'Kia Sportage',
  'Nissan Sunny',
  'Nissan Micra',
  'Honda Civic',
  'Honda City',
  'Mazda 3',
  'Mazda 2',
  'Mitsubishi Lancer',
  'Chevrolet Aveo',
  'Chevrolet Optra',
  'Volkswagen Golf',
  'Volkswagen Polo',
  'Skoda Octavia',
  'Renault Logan',
  'Renault Megane',
  'Peugeot 208',
  'Peugeot 301',
  'Suzuki Swift',
  'Suzuki Alto',
  'Ford Focus',
  'Ford Fiesta',
  'BMW 3 Series',
  'Mercedes-Benz C-Class',
];

const vehicleColorOptions = <String>[
  'أبيض',
  'أسود',
  'فضي',
  'رمادي',
  'أزرق',
  'أحمر',
  'أخضر',
  'أصفر',
  'بني',
  'بيج',
];
